steps:
- uses: actions/checkout@v3
- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.x'
- name: Install dependencies
  run: |
    python -m pip3 install --upgrade pip3
    pip3 install -e .[dev,streaming]
- name: Test with pytest
  run: |
    pytest -vv
  with:
    PROVIDER_URL: ${{ secrets.INFURA_API }}
    ETHEREUM_ETL_RUN_SLOW_TESTS=False
