name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip3 install --upgrade pip3
        pip3 install -e .[dev,streaming]
    - name: Test with pytest
      run: |
        export  PROVIDER_URL=${{ secrets.INFURA_API }}
        export  ETHEREUM_ETL_RUN_SLOW_TESTS=False
        pytest -vv

       
     
